[project]
name = "fastapi-project"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.120.3",
    "httpx>=0.28.1",
    "pytest>=8.4.2",
    "uvicorn[standard]>=0.38.0",
]
